### ISSUE TITLE
Point metadata is broken when writing JSON objects

### ISSUE THREAD

**Issue by avonwyss** [FarmBot/Farmbot-Web-App#1204]
# Expected Behavior
The metadata written comes back as JSON equivalent of the written data
-or-
The endpint rejects the data

# Actual Behavior
The data is modified and no longer valid JSON

# Steps to Reproduce
POST to /api/points:
```json
{
	"x": 0, 
	"y": 0, 
	"z": 0, 
	"pointer_type": "GenericPointer", 
	"name": "Test", 
	"meta": {
		"2019-05-20T22:00:00.000Z": {"rain": 0, "sun": 0.0, "temperature": 11.3, "wind": 5.6}, 
		"2019-05-20T23:00:00.000Z": {"rain": 0, "sun": 0.0, "temperature": 11.3, "wind": 4}
	}
}
```
# Results
```json
{
"id": 141117,
"created_at": "2019-05-21T17:20:46.462Z",
"updated_at": "2019-05-21T17:20:46.462Z",
"device_id": 4987,
"name": "Test",
"pointer_type": "GenericPointer",
"meta": {
"2019-05-20T22:00:00.000Z": "{"rain"=>0, "sun"=>0.0, "temperature"=>11.3, "wind"=>5.6}",
"2019-05-20T23:00:00.000Z": "{"rain"=>0, "sun"=>0.0, "temperature"=>11.3, "wind"=>4}"
},
"x": 0,
"y": 0,
"z": 0,
"radius": 25,
"discarded_at": null
}
```

**Comment by RickCarlino** [comment]
@avonwyss `point.meta` is an [hstore data type](https://www.postgresql.org/docs/9.1/hstore.html). From the PostgreSQL docs:

 > Keys and values are simply text strings.

We provide the meta column for storage of small data such as tags and labels. We do not want this column to be used as a substitute for an external database, or for storing large datasets of third party applications, such as time series data. For this reason, the API does not make an attempt to serialize/deserialize JSON objects. If you want to store small numbers of labels, tags or other simple data (strings, flags, etc) that's OK. Here are some options if you find this restriction limiting:

 * **Do nothing**. Don't change anything and (de)serialize JSON strings at your application layer. Please try to keep your total key size reasonable (<1500 characters).
 * **Use dot properties**. Use "dot properties" as seen in Redis/MQTT. Eg: `{"foo": {"bar": {"baz": "x"}}}` becomes `"foo.bar.baz": "x"`. You will still need to deserialize non-string types, but it may be easier to work with depending on your use case.
 * **Use free JSON hosting providers**. For medium-sized datasets, there are free services like [MyJSON](http://myjson.com/) or [JSONbin.io](https://jsonbin.io/) that will allow you to store arbitrary JSON objects in cloud storage for free without paying for server hosting.
 * **Host a third party database**. For extremely large datasets such as time series data, you can create a database off-site (or possibly on the same LAN as FarmBot) and:
    * reference the point by its ID in our database (eg: put a `farmbot_point_id` column in your database, similar to how we track the `openfarm_slug` in our database to track external resources from OpenFarm) -OR-
    * Store the primary key from your database inside of the `points.meta.my_db_primary_key`. This would allow you to use our API for search queries 

If you are storing more than ~1500 bytes of data, we ask that you store your data externally. **We currently do not enforce this limit, but might do so in the future.**

I would be interested to hear about your more about your use case. I am going to close this issue since the API is working as expected, but feel free to keep the discussion going if you have further comments or would like to tell me more about your use case.

**Comment by avonwyss** [comment]
@RickCarlino thank you for the details on the intentions of the `meta` data. I was aware that it is a hstore data type, but at the same time this is the only non-external suitable location I found for storing some data to be used between different farmwares.

That being said, I do understand your explanation but I still think that in this case the API should not accept the data if it is not just a dictionary of strings. As a consumer of the API the current behavior feels buggy. In general I believe that it is always best to fail early, not late - in this case when saving unsupported data types, not after retrieving them and getting unexpected data.

As to my use case: I want to implement smart watering based on the weather of the previous few days (rain, maybe also temperatures, sun, wind, and near-term forecast). Most weather services do not provide historical data (at least not for free), but they do provide current weather (and forecasts) - this also holds for the Swiss weather service I'm using. So I don't want to keep a full time series but just a sliding window of the past, say, 72 hours and some hours of forecast, available for retrieval for my watering computations (not a full time series). I do realize that this amount of data may be a bit over the suggested 1.5k but with a more compact representation it should actually not be too far off (e.g. 4 space-separated numbers, or something like this).

I'm not a fan of adding more dependencies to the mix, e.g. an external database, and I'd really like to have some limited "local" storage/DB to be available to the firmware code.

**Comment by avonwyss** [comment]
Yes, 422 seems to be a sensible response in that case.

Looking forward to FBOS v8 and the FarmwareEnvs! :)
