### ISSUE TITLE
GET api/logs/search not working as expected

### ISSUE THREAD

**Issue by amerkay** [FarmBot/Farmbot-Web-App#1354]
Continuing [discussion about /api/logs/search](https://github.com/RickCarlino/farmbot-web-app/commit/1eb2f5b96ad8b9f9cbd1b1280b944616f83c3b2c#r34592500).

## Expected Behavior
`GET api/logs/search?z=-334&y=662` should return filtered results (try just z=-334, too).

## Actual Behavior
I get about 700 results (not matching YZ) for the below code, while `app.get('logs')` returns 1000 as expected.

I expect just a handful at position (*, 662, -334) which is my watering tool mounting. Is it searching gte/lte instead of ==?

## Steps to Reproduce
Farmware code:
```py
logSearch = app.get('logs/search?z=-334&y=662')
device.log("logSearch count returned: {}".format(len(logSearch)), 'success', ['toast'])
```

FYI: I'm working on an auto-tool-unmount farmware. This way, it uses the logs to check last mounted tool, then return it. 

Thanks :)

**Comment by RickCarlino** [comment]
@amerkay As it turns out, we removed log filtering a while back (the app was using the `WebAppConfig` table to define search criteria). Since you have a need for the feature, I added it back to the app and did a hotfix deploy this morning. Details are available [here](https://github.com/FarmBot/Farmbot-Web-App/pull/1356). It currently supports equality, but not GT/LT operations.

 > FYI: I'm working on an auto-tool-unmount farmware. This way, it uses the logs to check last mounted tool, then return it.

I don't know if you saw this or not, but we added a `mounted_tool_id` column to the `devices` table to support this sort of thing. We're also going to add a sequence editor step to update this field:
![image](https://user-images.githubusercontent.com/1388608/62636014-66f44800-b8fe-11e9-976b-4b29cc2d781e.png)

Please let me know if you need help with anything else. It's always fun to see third party tools!

**Comment by amerkay** [comment]
Thanks, I'll give it a try! I've been playing around with your stack, great work you guys!

I got started with OS v7.0.1, a couple of weeks ago since it looked like v8-rc is still in the refactoring phase. It does look like the next update brings in many new features, exciting!

I am familiarizing myself with Farmwares, next is OpenCV and Tensorflow as my goal is to learn and contribute a CNN to farmbot within the next few months. 

I'll be starting a discussion on the forum to discuss what low hanging fruits for edge AI and improving farmbot. 

Would you be up for a quick phone call later today/tomorrow?

**Comment by RickCarlino** [comment]
@amerkay Thanks! You are correct, v8 still needs more QA. What time zone are you in? I'm in Chicago and work typical 9-5 hours. Please email me some times that work for you. Google hangouts is preferred. Email is my first name at farmbot.io . I look forward to speaking with you.
