### ISSUE TITLE
External MQTT?

### ISSUE THREAD

**Issue by radoslav-stefanov** [FarmBot/Farmbot-Web-App#1421]
Hi guys,

If I want to set an external MQTT, how exactly to configure FB, so it uses it? I tried updating MQTT_HOST, but it still tries to connect to the local MQTT. See log and my config bellow.

Basically I need to configure authentication and host location.

config
```
MQTT_HOST=192.168.10.1
API_HOST=192.168.10.10
API_PORT=3000
POSTGRES_PASSWORD=not_actual_value
DEVISE_SECRET=not_actual_value
ADMIN_PASSWORD=not_actual_value
SECRET_KEY_BASE=not_actual_value
RAILS_ENV=production
NO_EMAILS=TRUE
MQTT_WS=ws://192.168.10.1/ws
TRUSTED_DOMAINS=not_actual_value
RABBIT_MGMT_URL=http://192.168.10.1:80
```

log from farmbot-web-app_rabbit_jobs_1
```
W, [2019-09-09T18:48:04.730116 #1]  WARN -- #<Bunny::Session:0x5605d4a19fc0 admin@mqtt:5672, vhost=/, addresses=[mqtt:5672]>: Could not establish TCP connection to mqtt:5672: getaddrinfo: Name or service not known
Connecting to broker in 3 seconds. (#<Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts>)
```

Thanks!

results of `git log -1`
```
commit 973b403524a30dece3cd0bd42a97bba920599aba (HEAD -> master, origin/master)
Merge: 1bbc83c bb76d99
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Tue Aug 27 15:53:43 2019 -0500

    Merge pull request #1398 from RickCarlino/master

    Adjust CSP policy
```

**Comment by RickCarlino** [comment]
@radoslav-stefanov You are the first person to attempt this outside of FarmBot, Inc. so it is not a well documented feature, although we (FarmBot, Inc) _do_ setup our own servers this way, it is not something that any third-party self hosters have yet requested. Can you tell me more about your use case? Is it safe to assume that you are using RabbitMQ and not a third party alternative (eg: Mosca, Mosquitto, HiveMQ, etc..). The reason I ask is because although the Web App and many third party farmwares use MQTT, FarmBot OS uses AMQP internally, so it would not work with alternaitve brokers. RabbitMQ is the only broker that will support FarmBot currently.

With that being said, you must make sure that you set the (undocumented) `RABBITMQ_URL` ENV var. It will follow the format of `amqp://USERNAME:PASSWORD@HOST/VHOST`. The `HOST` must match the host set in `MQTT_HOST`.

Please let me know if that fixes your issue.

**Comment by radoslav-stefanov** [comment]
Hi @RickCarlino 

Thanks for the swift reply!

We are using HASSIO's addon https://github.com/hassio-addons/addon-mqtt/blob/master/README.md which has its own Mosquitto MQTT.

So I guess we should stick to the internal MQTT provided by FarmBot's docker-compose file?

**Comment by RickCarlino** [comment]
I'm actually not familiar with hass.io, but it looks cool! Is MQTT the only means of writing an integration?

Combining FarmBot into another product's MQTT server would be non-trivial because:

1. We would need to re-write the parts of FBOS that use AMQP.
2. We would need to re-visit all security related code since currently, RabbitMQ offloads all authn/authz tasks to the [RabbitMQ HTTP Auth Backend](https://github.com/rabbitmq/rabbitmq-auth-backend-http). 

If there was a specific use case you had in mind, I might be able to offer you alternative approaches. For the time being, I think it would be best to run the MQTT server provided by the docker-compose file. I'm very interested to hear about your use case, though.

**Comment by radoslav-stefanov** [comment]
Hi @RickCarlino 

I will ask someone from the group of people I work with to share insights on our use case. I am not that deeply familiar yet.

**Comment by RickCarlino** [comment]
Closing this issue for now, but still open to discussion as needed.
