### ISSUE TITLE
Farm designer grid line improvements

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1582]
The current minor grid lines are barely perceptible when zoomed to 0.5 or farther out, and with the new zoom animation they create a weird aliasing effect during the transition. When zoomed this far out, it would also become really helpful to have heavier-weight grid lines at 1000mm marks, which would probably be helpful when zoomed in too.

I suggest the following:
* Add new, even heavier weight grid lines at 1000mm marks (for all zoom levels)
* At scale(0.5) and smaller, hide the minor grid lines
* At scale(0.5) and smaller, bump up the 100mm and 1000mm grid line's weights so that they remain perceptible through the farthest out zoom levels

**Comment by webnos** [comment]
Hi, i worked on this issues, before pushing and create a pull request i'd like to be sure to have followed all the guidelines, can i contact you somehow?

Fabio.

**Comment by RickCarlino** [comment]
@webnos If you are ready to submit a pull request, you may do so, otherwise we are happy to help you on this issue thread. For code-related inquiries, Github is our preferred method of contact.

Here are some checks we run against PRs that you can run on your local setup:

Run Ruby unit tests:
```
sudo docker-compose run web rspec spec
```

Run Javascript linters to ensure that code meets style guidelines:
```
sudo docker-compose run web npm run linters
```

Run Javascript unit tests:
```
sudo docker-compose run web npm run test-slow
```

Run test coverage stats against Javascript codebase (should say "OK"- we can help you write tests if not):
```
sudo docker-compose run web rake coverage:run
```

If any of the above tests do not pass on your local machine, let us know in  this thread or in a new issue and we can help you fix the problem.

**Comment by webnos** [comment]
Hi @RickCarlino and thanks for the reply.

I've ran all the checks and they all pass except the Ruby unit tests, i'll attach a log cause i'm thinking this error is not due to my code changes and i don't know hot to fix it.

As for the branch i named it issue-1582, if you let me push it once we figure out the ruby unit test error i'll be more than happy to submit my first pull request. 

Also, assign the issue to me.

Have a nice weekend.
Fabio.

**Comment by RickCarlino** [comment]
@webnos It appears you have not setup your development environment completely (`bundle install`).

Please run:

```
sudo docker-compose run web bundle install
sudo docker-compose run web npm install
sudo docker-compose run web rake keys:generate
sudo docker-compose run -e RAILS_ENV=test web bundle exec rails db:setup
sudo docker-compose run -e RAILS_ENV=development web bundle exec rails db:setup
```

**Comment by webnos** [comment]
@RickCarlino thanks for the help, all tests passed.
I think i can now push the branch and open a pull request. 
I've already tried to push it but i don't have the right permissions.

Let me know if you want me to try something else before the push.

**Comment by RickCarlino** [comment]
@webnos You need to fork this repository and create a branch within your personal fork. Only FarmBot employees can push to the official repository. Github maintains [documentation](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests) on how to accomplish this.

**Comment by webnos** [comment]
@RickCarlino first time i'm using this workflow. I'll read the docs and be back once all is setup properly.
Thanks
