### ISSUE TITLE
Add "Watered" / "Unwatered" Plant Statuses to MARK AS / Criteria

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1719]
Based on [this discussion](https://forum.farmbot.org/t/optimizing-sequences-with-data-records/5880) in the forum.

**Comment by roryaronson** [comment]
@RickCarlino as we discussed on Thursday(?) I think we're better off keeping the current plant status field exclusively for "life stages", and we might want to rename it as such. Otherwise the user would need to pick tracking either life stage OR water, but couldn't do both for the same plant.

To give users the ability to track other statuses, even more than just life stage and water, its probably best to offer a "Custom" write-in option in MARK AS that would use the meta field under the hood. Something like this:
<img width="676" alt="Screen Shot 2020-03-05 at 9 39 43 AM" src="https://user-images.githubusercontent.com/5524043/76266485-db8cbd80-6224-11ea-84af-64dccdd5df18.png">

Where **CUSTOM FIELD** and **VALUE** correspond to key/value pairs in `meta`. This would allow any number of things to be tracked, using any number of values, which will satisfy that user in the forum and allow for a lot of other use cases.

Users would then be able to select plants matching their custom key/value pairs using the advanced criteria options in the works.

**Comment by RickCarlino** [comment]
That makes sense @roryaronson . I will close this card and create a new based on the mockup you've provided.
