### ISSUE TITLE
Question about adding a feature (from a python dev)

### ISSUE THREAD

**Issue by KyryloKaralyus** [FarmBot/Farmbot-Web-App#1748]
Hello there, I'm a beginner developer with interest in permaculture and open source movements and I have thought about adding a few features to the web-app:

1. when picking the next plant, drop-down list sorts all shown plants by how [allopathic(symbiotic/friendly)](https://deepgreenpermaculture.com/companion-planting/) they are to the ones already selected (from best companion plants to outright enemies that would struggle to share the same soil together).
2. the algorithm that automatically finds spots for selected seeds utilizing the most space while putting good companion plants close together. 
3. a function that combines the previous two - automatic configuration finder for "making the most money out of the land" (potentially based on location - would plant kale everywhere if you're in a big city where it's profitable), "getting the most variety", "variety of spicy veggies", "variety of most nutritionally dense heirlooms", etc. 
4. a finder for the cheapest/most local/best quality organic seeds that could order the ones from your garden configuration?

I thought of all these both because they seem to be useful and because they seem to be perfect intermediate programmer exercises. It seems like the web app is developed with ruby and typescript (am I right?), but I'm currently studying **python as my first and only language** for now. And so I'm wondering about the best resolution:

- Should I just lay this off until I'm good with ruby and typescript or are you aware of any simple way for a python program to interact with existing web-app? 
- Even if I have all the API I need, are you even considering adding pieces of python? 
- I heard wrappers could be a good solution, is there anyone with experience?
Please point me in the right direction so I can make this a reality. 
Sorry if the answer seems obvious, I'm not very experienced. 

Also, I've read that farmbot _software_ operates under MIT license, but it's not clear to me whether that means one can operate the same business setting farmbots up like founders do in California headquarters. If yes, is there a paper/post on how you did your research regarding where to manufacture all the parts? I live in Ukraine and I'm guessing it can be in the Chinese price-range. 
Again, sorry if I missed the obvious answers.

Feel free to reply here or at iLLevensko@gmail.com
Have a fabulous sweet day!

**Comment by RickCarlino** [comment]
> adding a few features to the web-app

These are all great feature ideas, and some of them are planned for future releases. You may want to take a look at [OpenFarm](https://openfarm.cc) ([Github](https://github.com/openfarmcc/OpenFarm)) if you have not done so already- it is a related project that shares many of these ambitions. The project is currently without a lead maintainer so things are moving a bit slower than they have in the past. Many of the ideas you suggest are already on the road map. If you have ever used FarmBot's farm designer tool you have already used OpenFarm- OpenFarm powers the plant search API of our web app.

 > are you aware of any simple way for a python program to interact with existing web-app?

Yes, you can write a wrapper library in Python. This is a great way to create features outside of the FarmBot codebase. You can add almost any feature you want this way, since your library would live outside of the FarmBot repository.

Here's the course of action I would recommend:

1. Read the [FarmBot Developer Documentation](https://developer.farm.bot/docs). The document was intended to be read from start-to-finish (rather than as a reference guide). As the author of the documentation, I would be happy to answer any questions you have. The [forum](https://forum.farmbot.org/) is a good place for general discussion and I check messages there almost every day.
2. Once you have an understanding of FarmBot's architecture, you can interact with the application (and device) via the [REST API](https://developer.farm.bot/docs/rest-api) and [message broker](https://developer.farm.bot/docs/message-broker).

We've made some examples of this in the past:

 * [Controlling FarmBot remotely via Javascript](https://github.com/FarmBot-Labs/remote-control-example)
 * [Controlling FarmBot remotely via Python](https://github.com/FarmBot-Labs/FarmBot-Python-Examples)

 > are you even considering adding pieces of python?

Python would add new dependencies to the project and reduce consistency. I cannot accept pull requests written in Python. I would instead encourage you to learn Ruby and Typescript. They are both excellent programming languages.

 > I've read that farmbot software operates under MIT license, but it's not clear to me whether that means one can operate the same business setting farmbots up like founders do in California headquarters.

The MIT license is a "permissive license", so it puts very few restrictions on what you can do with the software. Many people use FarmBot for commercial purposes. You can read more about software freedom [here](https://meta.farm.bot/docs/respecting-your-freedom).

Please note that our marketing material (logos, photos, blog posts, etc..) are _not_ open source and although they can be shared and used by individuals, they cannot be used for commercial use. This is covered in our [meta documentation](https://meta.farm.bot/docs/respecting-your-freedom#section-maintaining-integrity) under the "Maintaining Integrity" section.

 > If yes, is there a paper/post on how you did your research regarding where to manufacture all the parts?

Not at this time.
