### ISSUE TITLE
No connection but message says "up and running"

### ISSUE THREAD

**Issue by GuidoCram** [FarmBot/Farmbot-Web-App#1901]
# Expected Behavior
I logged into my.farm.bot while the farmbot was offline / off power. I got a red cross about connectivity.

# Actual Behavior
I got also a green bullet that everything is up and running

# Steps to Reproduce
- power off farmbot
- log into my.farm.bot
- check the upper left corner of the screen

# Results of `git log -1`

Run `git log -1` and paste the results here.

Screenshot:
![2020-07-25_12-38-36](https://user-images.githubusercontent.com/50169830/88455294-86201880-ce74-11ea-9980-811ed7cd0b42.png)

![image](https://user-images.githubusercontent.com/50169830/88455284-73a5df00-ce74-11ea-829d-71efe629fd41.png)

**Comment by RickCarlino** [comment]
@GuidoCram I can understand why you find this confusing. Below I've made a diagram that explains the situation:
![image](https://user-images.githubusercontent.com/1388608/88463425-54a94c00-ce78-11ea-84a4-dc7789b12360.png)

The problem is that the last message sent from your device was `Farmbot is up and running!` and then the device went offline.

For the _actual_ connectivty status, you should refer to the button that says CONNECTIVITY (bottom right of screenshot).

With that being said, it looks like you're having device trouble. When did the problems start? Did they happen after an OS upgrade or change to the LAN? Which model are you currently running?

**Comment by GuidoCram** [comment]
I know the farmbot was not connected. It's just weird that the interface
shows the last log (green) which gives the user the indication all is fine.
When actually it is not. No big deal, but from a user interaction
perspective it is weird.

The farmbot has been offline and off power for some time. I flashed the
memory card again and it's running fine now. Model 1.4.


Met vriendelijke groet,
Guido Cramwinckel.



Op za 25 jul. 2020 om 20:16 schreef Rick Carlino <notifications@github.com>:

**Comment by RickCarlino** [comment]
OK, glad to hear your device is running fine @GuidoCram . I will forward this issue to @roryaronson (who usually handles UX matters) and discuss it with him on Monday. Have a nice weekend! :tada:

**Comment by roryaronson** [comment]
Thanks for reporting this @GuidoCram. To make this less confusing, whenever the bot is offline we could replace the most recent log with a gray saucer and message that reads "FarmBot is offline", similar to the "No logs yet" message on brand new accounts.

What do you think?
<img width="1440" alt="Screen Shot 2020-07-27 at 7 29 28 PM" src="https://user-images.githubusercontent.com/5524043/88612191-802a6300-d03f-11ea-8e01-3c58a875745e.png">

**Comment by GuidoCram** [comment]
Good solution. As a user, I'm not interested in the actual last message but
in the current status. And the bot is offline, so this is a very good
solution.


Met vriendelijke groet,
Guido Cramwinckel.



Op di 28 jul. 2020 om 04:31 schreef Rory Aronson <notifications@github.com>:

**Comment by roryaronson** [comment]
Ok great, thanks for the feedback. We'll implement the solution I proposed within the next few weeks!

**Comment by roryaronson** [comment]
Thanks again for the suggestion @GuidoCram, this is now deployed to my.farm.bot
