### ISSUE TITLE
Local server-host: Bundle is locked to mimemagic (0.3.5).

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/Farmbot-Web-App#2121]
# Expected Behavior
All Gems are successfully installed when running the command `sudo docker-compose run web bundle install`
# Actual Behavior
![image](https://user-images.githubusercontent.com/23129562/112690532-361ea900-8e7c-11eb-830b-1bb715df3b13.png)

Unfortunately I've got very little knowledge about things like gems and dependencies, but it looks like this one needs to be updated.
running `sudo docker-compose run web bundle update mimemagic` fixed it for me by updating to v 0.3.10.

**Comment by RickCarlino** [comment]
@AscendFB The problem is with RubyGems rather than FarmBot, unfortunately. Rather than immediately attempt to fix the problem, we are waiting for the larger Rails community to figure out a solution. I imagine the issue will be solved within the next few days. You can read more about it by searching the web for "Rails mimemagic licensing issue".

**Comment by AscendFB** [comment]
Hey @RickCarlino, thanks for that quick reply. That sounds good and reasonable to me and I didn't know you are already informed. 🙂
