### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by KizziePig** [FarmBot/Farmbot-Web-App#566]
# Expected Behavior
When starting the api with 
rails api:start I expected it to end up Listening on <myIP>:3000 but below is the actual output although I believe I've followed the steps. Note that I'm using an AWS Linux box (essentially a Centos 6 machine).

# Actual Behavior
05:18:43 rails.1   | Listening on 0.0.0.0:3000, CTRL+C to stop
05:18:43 logger.1  | W, [2017-12-12T05:18:43.039206 #26610]  WARN -- #<Bunny::Session:0x5bafe28 guest@localhost:5672, vhost=/, addresses=[localhost:5672]>: Could not establish TCP connection to localhost:5672: Connection refused - connect(2) for 127.0.0.1:5672
05:18:43 logger.1  | /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/bunny-2.7.2/lib/bunny/session.rb:329:in `rescue in start': Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/bunny-2.7.2/lib/bunny/session.rb:297:in `start'
05:18:43 logger.1  |    from /usr/local/Farmbot-Web-App/app/models/transport.rb:10:in `connection'
05:18:43 logger.1  |    from /usr/local/Farmbot-Web-App/app/models/transport.rb:15:in `log_channel'
05:18:43 logger.1  |    from lib/log_service.rb:6:in `<top (required)>'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:34:in `load'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:34:in `perform'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
05:18:43 logger.1  |    from /usr/local/rvm/gems/ruby-2.4.2@farmbot-web-app/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
05:18:43 logger.1  |    from bin/rails:4:in `require'
05:18:43 logger.1  |    from bin/rails:4:in `<main>'
05:18:43 logger.1  | exited with code 1
0

**Comment by RickCarlino** [comment]
@KizziePig You have indeed spotted a bug in the setup instructions.

# What Happened?

Due to some changes in the codebase this week, the `README.md` setup instructions became outdated. The reason you are seeing the error is that the setup instructions were (incorrectly) cloning the `staging` branch, which is unstable and only used by members of the core team.

# How to Fix

I have updated the `README.md` to reflect the new setup.

 * If you are familiar with Git, you can switch to the `master` branch (instead of `staging`) and re-run setup.
 * If you are unfamiliar with Git branching commands, I would recommend deleting the current setup and starting over with the new setup directions. They have been updated to prevent the error above.

Thanks for bringing this to our attention. Please let us know if you need further assistance.
