### ISSUE TITLE
MQTT server/address moved?

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/Farmbot-Web-App#730]
# Expected Behavior
Connecting to MQTT server at mqtt.farmbot.io:1883, or as it used to be before the MQTT change my.farmbot.io:1883.
# Actual Behavior
![image](https://user-images.githubusercontent.com/23129562/37565836-07aca4fa-2ab1-11e8-86c0-86bd3fc88a7f.png)
I managed to connect to `brisk-bear.rmq.cloudamqp.com` instead.

My question: Does this MQTT address stay like this? There are some places where mqtt.farmbot.io is documented as the connecting address (https://github.com/AscendFB/FarmBot-Python-Examples , https://github.com/FarmBot/farmbot-js/wiki/Using-Raw-MQTT).

**Comment by RickCarlino** [comment]
Hi @AscendFB ,

 > I managed to connect to brisk-bear.rmq.cloudamqp.com instead.

This is correct. `mqtt.farmbot.io` was decommissioned a few months ago in favor of managed hosting. The MQTT host for your device is `brisk-bear.rmq.cloudamqp.com`. If you are building a production critical application, the safest way to resolve the host address is by accessing the `mqtt` claim of your access token. For hobby projects or debugging, it's probably not a huge deal and you can leave it hardcoded.

 > Does this MQTT address stay like this?

No, it will change in the future, although not often. You should treat the `mqtt` value of your token as if it were dynamic.

If you have uptime requirements or plan on sharing the app with other users, use the `mqtt` claim of your token rather than a hardcoded URL. The value of the `mqtt` host may change in the future and not every user will have the same MQTT host. **This is especially true for users that are hosted on 3rd party servers**.

The `token.unencoded.mqtt` value of your auth token will always be correct.

 > There are some places where mqtt.farmbot.io is documented as the connecting address

Thanks for the heads up! It looks like the `farmbot-js` wiki still had some outdated information which I updated right now.

In the case of the link to [your fork](https://github.com/AscendFB/FarmBot-Python-Examples) it looks like you are behind [FarmBot-Labs/FarmBot-Python-Examples repo](https://github.com/FarmBot-Labs/FarmBot-Python-Examples) by one month. You should be able to `git pull ...` the latest docs from upstream.

Thanks again for letting us know about this and as always.

Please do show us what you build when you are finished! :tada:

Closing this issue, but feel free to keep the discussion going if there are other issues with the MQTT host.

**Comment by AscendFB** [comment]
> In the case of the link to your fork it looks like you are behind FarmBot-Labs/FarmBot-Python-Examples repo by one month. You should be able to git pull ... the latest docs from upstream.
Oh sorry, thats right. Looks like I messed up the browser tabs at this time. 

> No, it will change in the future, although not often. You should treat the mqtt value of your token as if it were dynamic.
Alright, I will keep that in mind for the next time. I just wasn't able to find any indications that the address changed recently.
Thanks for helping out!
